### ISSUE TITLE
Custom fetch

### ISSUE THREAD

**Issue by KirillPd** [all-bear/react-native.advanced-fetch#8]
Currently we're using the react native fetch to send a data. It would be better to have an option to use an another custom interface instead

**Comment by all-bear** [comment]
@KirillPd please check the commit, do you agree with provided solution ?

**Comment by KirillPd** [comment]
@all-bear Posted my opinion [here](https://github.com/all-bear/react-native.advanced-fetch/commit/63eaae477860736441b1237ceb7258de2ed00db9#comments)

**Comment by all-bear** [comment]
@KirillPd will close without your changes for now because of:

we can implement custom fetch different for for every request on cached fetch - it's fine and we will have no problems with it

but in a case of delayed fetch we will have a problem, if we pass custom fetch to delayed fetch request we will need to encode this custom fetch and store it in storage until this request will process but encoding function (custom fetch) will bring more problems for us then achievements
